Repository WarsWorld/WarsWorld, pull requests merged in 2023-06, with the labels that each got.

#138 Updating navbar closer to Figma design
  public/img/layout/APC_MSide-0.png
  public/img/layout/Cruiser-0.png
  public/img/layout/MdTank_MSide-0.png
  public/img/layout/NeoTank_MSide-0.png
  public/img/layout/Stealth-0.png
  public/img/layout/Sub-0.png
  src/frontend/components/Footer.tsx
  src/frontend/components/Home.tsx
  src/frontend/components/Home/Banner.tsx
  src/frontend/components/Navbar/NavGroup.tsx
  src/frontend/components/Navbar/NavGroupMobile.tsx
  src/frontend/components/Navbar/NavItem.tsx
  src/frontend/components/Navbar/NavLinks.tsx
  src/frontend/components/Navbar/NavLinksMatches.tsx
  src/frontend/components/Navbar/NavLinksMobile.tsx
  src/frontend/components/Navbar/NavMenuMatches.tsx
  src/frontend/components/Navbar/Navbar.tsx
  src/frontend/components/Navbar/index.ts
  src/frontend/components/layout.tsx
  src/frontend/components/match/MatchRow.tsx
  src/frontend/styles/animations.sass
  src/frontend/styles/globals.scss
  src/frontend/styles/grid/global.scss
  src/frontend/styles/pages/homeBanner.scss
  src/frontend/styles/pages/index.scss
  src/frontend/styles/template/layout.scss
  src/pages/index.tsx
  src/pages/your-matches.tsx
Labels: ✨ goal: improvement, 💪 skill: tailwind/styling

#145 General code optimizations and clean-up
  src/frontend/components/Footer.tsx
  src/frontend/components/Home.tsx
  src/frontend/components/Home/Banner.tsx
  src/frontend/components/Home/SmallContainer.tsx
  src/frontend/components/Home/ThreeLinesText.tsx
  src/frontend/components/IngameInfo.tsx
  src/frontend/components/Navbar/NavGroup.tsx
  src/frontend/components/Navbar/Navbar.tsx
  src/frontend/components/layout.tsx
  src/frontend/components/match/MatchRow.tsx
  src/frontend/components/match/PlayerBox.tsx
  src/frontend/styles/pages/homeBanner.scss
  src/frontend/styles/template/layout.scss
  src/pages/howtoplay/index.tsx
  src/pages/index.tsx
  src/pages/match/[matchId].tsx
  src/pages/your-matches.tsx
Labels: 🟩 difficulty: low, ✨ goal: improvement, 🛠 goal: fix, 💻 aspect: code, 💪 skill: typescript, 💪 skill: tailwind/styling

#150 News Page Updates
  package-lock.json
  package.json
  public/img/layout/newsPage/featuredImg.png
  public/img/layout/newsPage/newsPlaceholder1.png
  public/img/layout/newsPage/newsPlaceholder2.png
  public/img/layout/newsPage/newsPlaceholder3.png
  public/img/layout/newsPage/newsPlaceholder4.png
  src/frontend/components/Navbar/NavGroup.tsx
  src/frontend/components/Navbar/NavGroupMobile.tsx
  src/frontend/components/layout/ArticleLinkCard.tsx
  src/frontend/components/layout/ArticleSection.tsx
  src/frontend/components/layout/LinkCard.tsx
  src/frontend/components/news/FeaturedNews.tsx
  src/pages/home/LoggedHome.tsx
  src/pages/howtoplay.tsx
  src/pages/news/index.tsx
Labels: 🟨 difficulty: medium, ⭐ goal: addition, ✨ goal: improvement, 💻 aspect: code, 💪 skill: typescript, 💪 skill: tailwind/styling

#153 Adds 1v1 match component
  public/img/CO/smoothFull/Awds-adder.webp
  public/img/CO/smoothFull/Awds-colin.webp
  public/img/CO/smoothFull/Awds-eagle.webp
  public/img/CO/smoothFull/Awds-flak.webp
  public/img/CO/smoothFull/Awds-grimm.webp
  public/img/CO/smoothFull/Awds-grit.webp
  public/img/CO/smoothFull/Awds-hachi.webp
  public/img/CO/smoothFull/Awds-hawke.webp
  public/img/CO/smoothFull/Awds-jake.webp
  public/img/CO/smoothFull/Awds-javier.webp
  public/img/CO/smoothFull/Awds-jess.webp
  public/img/CO/smoothFull/Awds-jugger.webp
  public/img/CO/smoothFull/Awds-kanbei.webp
  public/img/CO/smoothFull/Awds-kindle.webp
  public/img/CO/smoothFull/Awds-koal.webp
  public/img/CO/smoothFull/Awds-lash.webp
  public/img/CO/smoothFull/Awds-max.webp
  public/img/CO/smoothFull/Awds-nell.webp
  public/img/CO/smoothFull/Awds-olaf.webp
  public/img/CO/smoothFull/Awds-sonja.webp
  public/img/CO/smoothFull/Awds-von-bolt.webp
  public/img/matchCard/clock.png
  public/img/matchCard/eye.png
  public/img/matchCard/liveDot.png
  public/img/matchCard/mapBgDemo.png
  public/img/matchCard/star.png
  src/frontend/components/Navbar/NavMenuMatches.tsx
  src/frontend/components/match/MatchCard.tsx
  src/frontend/components/match/MatchSection.tsx
  src/frontend/components/match/PlayerNameBar.tsx
  src/frontend/utils/enums.ts
  src/frontend/utils/mocks/mapDataMock.ts
  src/frontend/utils/mocks/matchDataMock.ts
  src/frontend/utils/mocks/playerInMatchMock.ts
  src/pages/home/BasicHome.tsx
  src/pages/sample-matches.tsx
  src/pages/your-matches.tsx
  src/shared/types/component-data.ts
  src/shared/types/server-match-state.d.ts
  tailwind.config.js
Labels: ⭐ goal: addition, 💻 aspect: code

#157 Fixing navbar bug
  src/frontend/components/Navbar/NavGroup.tsx
  src/frontend/components/Navbar/NavGroupMobile.tsx
  src/frontend/components/Navbar/NavItem.tsx
  src/frontend/components/Navbar/NavMenuMatches.tsx
  src/frontend/components/Navbar/Navbar.tsx
Labels: 🛠 goal: fix

#158 Update to sample match page to make cards responsive
  src/frontend/components/layout/Banner.tsx
  src/frontend/components/match/MatchCard.tsx
  src/frontend/components/match/MatchSection.tsx
  src/frontend/components/match/PlayerNameBar.tsx
  src/pages/article.tsx
  src/pages/sample-matches.tsx
Labels: 💪 skill: tailwind/styling

#162 Render Markdown for How to play guides and future news articles/balance patches
  package-lock.json
  package.json
  src/frontend/components/layout/Banner.tsx
  src/frontend/styles/global.scss
  src/frontend/styles/pages/articles.module.scss
  src/frontend/utils/articleScript.ts
  src/frontend/utils/articles/flak.md
  src/frontend/utils/articles/lash.md
  src/pages/article.tsx
  src/pages/articles/[id].tsx
  src/pages/home/BasicHome.tsx
Labels: 🟩 difficulty: low, ⭐ goal: addition, 💪 skill: tailwind/styling
